package org.tensorflow.lite.examples.classification

class Traductor {


    fun Traduce(text:String): String{
        when(text){
            "background" -> return "antecedentes"
            "tench" -> return "tenca"
            "goldfish" -> return "pez de colores"
            "great white shark" -> return "gran tiburón blanco"
            "tiger shark" -> return "tiburón tigre"
            "hammerhead" -> return "cabeza de martillo"
            "electric ray" -> return "rayo electrico"
            "stingray" -> return "mantarraya"
            "cock" -> return "polla"
            "hen" -> return "gallina"
            "ostrich" -> return "avestruz"
            "brambling" -> return "pinzón"
            "goldfinch" -> return "jilguero"
            "house finch" -> return "pinzón de casa"
            "junco" -> return "junco"
            "indigo bunting" -> return "empavesado índigo"
            "robin" -> return "Robin"
            "bulbul" -> return "bulbul"
            "jay" -> return "arrendajo"
            "magpie" -> return "urraca"
            "chickadee" -> return "paro"
            "water ouzel" -> return "agua ouzel"
            "kite" -> return "cometa"
            "bald eagle" -> return "Águila calva"
            "vulture" -> return "buitre"
            "great grey owl" -> return "gran búho gris"
            "European fire salamander" -> return "Salamandra europea"
            "common newt" -> return "tritón común"
            "eft" -> return "eft"
            "spotted salamander" -> return "salamandra manchada"
            "axolotl" -> return "ajolote"
            "bullfrog" -> return "rana mugidora"
            "tree frog" -> return "rana de árbol"
            "tailed frog" -> return "rana de cola"
            "loggerhead" -> return "necio"
            "leatherback turtle" -> return "tortuga laúd"
            "mud turtle" -> return "tortuga de barro"
            "terrapin" -> return "tortuga de agua dulce"
            "box turtle" -> return "tortuga de caja"
            "banded gecko" -> return "gecko congregado"
            "common iguana" -> return "iguana común"
            "American chameleon" -> return "Camaleón americano"
            "whiptail" -> return "Whiptail"
            "agama" -> return "agama"
            "frilled lizard" -> return "lagarto con volantes"
            "alligator lizard" -> return "lagarto cocodrilo"
            "Gila monster" -> return "monstruo Gila"
            "green lizard" -> return "Lagartija verde"
            "African chameleon" -> return "Camaleón africano"
            "Komodo dragon" -> return "Dragon de Komodo"
            "African crocodile" -> return "Cocodrilo africano"
            "American alligator" -> return "Cocodrilo americano"
            "triceratops" -> return "triceratops"
            "thunder snake" -> return "serpiente de trueno"
            "ringneck snake" -> return "serpiente ringneck"
            "hognose snake" -> return "serpiente de cerdo"
            "green snake" -> return "serpiente verde"
            "king snake" -> return "Rey Serpiente"
            "garter snake" -> return "serpiente de liga"
            "water snake" -> return "serpiente de agua"
            "vine snake" -> return "serpiente de vid"
            "night snake" -> return "serpiente de noche"
            "boa constrictor" -> return "Boa constrictor"
            "rock python" -> return "pitón de roca"
            "Indian cobra" -> return "Cobra india"
            "green mamba" -> return "mamba verde"
            "sea snake" -> return "serpiente de mar"
            "horned viper" -> return "víbora cornuda"
            "diamondback" -> return "diamante"
            "sidewinder" -> return "Sidewinder"
            "trilobite" -> return "trilobite"
            "harvestman" -> return "cosechador"
            "scorpion" -> return "escorpión"
            "black and gold garden spider" -> return "araña de jardín negra y dorada"
            "barn spider" -> return "araña de granero"
            "garden spider" -> return "araña de jardín"
            "black widow" -> return "viuda negra"
            "tarantula" -> return "tarántula"
            "wolf spider" -> return "araña lobo"
            "tick" -> return "garrapata"
            "centipede" -> return "ciempiés"
            "black grouse" -> return "urogallo negro"
            "ptarmigan" -> return "perdiz nival"
            "ruffed grouse" -> return "urogallo"
            "prairie chicken" -> return "pollo de la pradera"
            "peacock" -> return "pavo real"
            "quail" -> return "codorniz"
            "partridge" -> return "perdiz"
            "African grey" -> return "Gris africano"
            "macaw" -> return "guacamayo"
            "sulphur-crested cockatoo" -> return "cacatúa de cresta de azufre"
            "lorikeet" -> return "lorikeet"
            "coucal" -> return "cucal"
            "bee eater" -> return "comedor de abejas"
            "hornbill" -> return "cálao"
            "hummingbird" -> return "colibrí"
            "jacamar" -> return "jacamar"
            "toucan" -> return "tucán"
            "drake" -> return "pato"
            "red-breasted merganser" -> return "pollo de agua de pecho rojo"
            "goose" -> return "ganso"
            "black swan" -> return "cisne negro"
            "tusker" -> return "elefante"
            "echidna" -> return "equidna"
            "platypus" -> return "ornitorrinco"
            "wallaby" -> return "Wallaby"
            "koala" -> return "coala"
            "wombat" -> return "wombat"
            "jellyfish" -> return "Medusa"
            "sea anemone" -> return "anémona de mar"
            "brain coral" -> return "coral cerebro"
            "flatworm" -> return "gusano plano"
            "nematode" -> return "nematodo"
            "conch" -> return "concha"
            "snail" -> return "caracol"
            "slug" -> return "babosa"
            "sea slug" -> return "babosa de mar"
            "chiton" -> return "chitona"
            "chambered nautilus" -> return "nautilo con cámara"
            "Dungeness crab" -> return "cangrejo Dungeness"
            "rock crab" -> return "cangrejo de roca"
            "fiddler crab" -> return "cangrejo violinista"
            "king crab" -> return "cangrejo real"
            "American lobster" -> return "Langosta americana"
            "spiny lobster" -> return "langosta espinosa"
            "crayfish" -> return "cangrejo de río"
            "hermit crab" -> return "cangrejo ermitaño"
            "isopod" -> return "isópodo"
            "white stork" -> return "cigüeña blanca"
            "black stork" -> return "cigüeña negra"
            "spoonbill" -> return "espátula"
            "flamingo" -> return "flamenco"
            "little blue heron" -> return "Garza Azul"
            "American egret" -> return "Garceta americana"
            "bittern" -> return "avetoro"
            "crane" -> return "grua"
            "limpkin" -> return "cojera"
            "European gallinule" -> return "Gallinule europeo"
            "American coot" -> return "Focha americana"
            "bustard" -> return "avutarda"
            "ruddy turnstone" -> return "ruddy vuelvepiedra"
            "red-backed sandpiper" -> return "lavandera de lomo rojo"
            "redshank" -> return "archibebe"
            "dowitcher" -> return "dowitcher"
            "oystercatcher" -> return "ostrero"
            "pelican" -> return "pelícano"
            "king penguin" -> return "pingüino real"
            "albatross" -> return "albatros"
            "grey whale" -> return "ballena gris"
            "killer whale" -> return "Orca"
            "dugong" -> return "dugong"
            "sea lion" -> return "León marino"
            "Chihuahua" -> return "Chihuahua"
            "Japanese spaniel" -> return "Spaniel Japonés"
            "Maltese dog" -> return "Perro maltés"
            "Pekinese" -> return "pekinés"
            "Shih-Tzu" -> return "Shih-Tzu"
            "Blenheim spaniel" -> return "Blenheim Spaniel"
            "papillon" -> return "Papillon"
            "toy terrier" -> return "terrier de juguete"
            "Rhodesian ridgeback" -> return "Ridgeback de Rodesia"
            "Afghan hound" -> return "Sabueso afgano"
            "basset" -> return "afloramiento"
            "beagle" -> return "beagle"
            "bloodhound" -> return "sabueso"
            "bluetick" -> return "bluetick"
            "black-and-tan coonhound" -> return "Coonhound negro y fuego"
            "Walker hound" -> return "Sabueso caminante"
            "English foxhound" -> return "Foxhound Inglés"
            "redbone" -> return "redbone"
            "borzoi" -> return "borzoi"
            "Irish wolfhound" -> return "Perro lobo irlandés"
            "Italian greyhound" -> return "Galgo italiano"
            "whippet" -> return "lebrel"
            "Ibizan hound" -> return "Sabueso ibicenco"
            "Norwegian elkhound" -> return "Elkhound noruego"
            "otterhound" -> return "sabueso"
            "Saluki" -> return "Saluki"
            "Scottish deerhound" -> return "Ciervo escocés"
            "Weimaraner" -> return "Weimaraner"
            "Staffordshire bullterrier" -> return "Staffordshire Bull Terrier"
            "American Staffordshire terrier" -> return "American Staffordshire Terrier"
            "Bedlington terrier" -> return "Bedlington terrier"
            "Border terrier" -> return "Border terrier"
            "Kerry blue terrier" -> return "Kerry blue terrier"
            "Irish terrier" -> return "Terrier irlandés"
            "Norfolk terrier" -> return "Terrier de Norfolk"
            "Norwich terrier" -> return "Terrier de Norwich"
            "Yorkshire terrier" -> return "Yorkshire terrier"
            "wire-haired fox terrier" -> return "fox terrier de pelo de alambre"
            "Lakeland terrier" -> return "Lakeland terrier"
            "Sealyham terrier" -> return "Sealyham terrier"
            "Airedale" -> return "Airedale"
            "cairn" -> return "mojón"
            "Australian terrier" -> return "Terrier australiano"
            "Dandie Dinmont" -> return "Dandie Dinmont"
            "Boston bull" -> return "Toro de Boston"
            "miniature schnauzer" -> return "Schnauzer miniatura"
            "giant schnauzer" -> return "Schnauzer gigante"
            "standard schnauzer" -> return "Schnauzer estándar"
            "Scotch terrier" -> return "Terrier escocés"
            "Tibetan terrier" -> return "Terrier tibetano"
            "silky terrier" -> return "terrier sedoso"
            "soft-coated wheaten terrier" -> return "terrier de trigo de capa suave"
            "West Highland white terrier" -> return "West Highland White Terrier"
            "Lhasa" -> return "Lhasa"
            "flat-coated retriever" -> return "perro perdiguero de capa plana"
            "curly-coated retriever" -> return "perro perdiguero rizado"
            "golden retriever" -> return "golden retriever"
            "Labrador retriever" -> return "Labrador retriever"
            "Chesapeake Bay retriever" -> return "Chesapeake Bay retriever"
            "German short-haired pointer" -> return "Puntero de pelo corto alemán"
            "vizsla" -> return "vizsla"
            "English setter" -> return "Setter inglés"
            "Irish setter" -> return "Setter irlandés"
            "Gordon setter" -> return "Setter Gordon"
            "Brittany spaniel" -> return "Bretaña Spaniel"
            "clumber" -> return "clumber"
            "English springer" -> return "Springer Inglés"
            "Welsh springer spaniel" -> return "Springer Spaniel Galés"
            "cocker spaniel" -> return "Cocker"
            "Sussex spaniel" -> return "Spaniel de Sussex"
            "Irish water spaniel" -> return "Spaniel de agua irlandés"
            "kuvasz" -> return "Kuvasz"
            "schipperke" -> return "Schipperke"
            "groenendael" -> return "Groenendael"
            "malinois" -> return "malinois"
            "briard" -> return "briard"
            "kelpie" -> return "Kelpie"
            "komondor" -> return "komondor"
            "Old English sheepdog" -> return "Viejo perro pastor inglés"
            "Shetland sheepdog" -> return "Perro pastor de Shetland"
            "collie" -> return "collie"
            "Border collie" -> return "Border Collie"
            "Bouvier des Flandres" -> return "Bouvier des Flandres"
            "Rottweiler" -> return "Rottweiler"
            "German shepherd" -> return "Pastor alemán"
            "Doberman" -> return "Caballero"
            "miniature pinscher" -> return "pinscher miniatura"
            "Greater Swiss Mountain dog" -> return "Gran perro de montaña suizo"
            "Bernese mountain dog" -> return "Perro de montaña de Bernese"
            "Appenzeller" -> return "Appenzeller"
            "EntleBucher" -> return "EntleBucher"
            "boxer" -> return "Boxer"
            "bull mastiff" -> return "mastín de toro"
            "Tibetan mastiff" -> return "mastín tibetano"
            "French bulldog" -> return "Bulldog francés"
            "Great Dane" -> return "Gran Danés"
            "Saint Bernard" -> return "San Bernardo"
            "Eskimo dog" -> return "Perro esquimal"
            "malamute" -> return "malamute"
            "Siberian husky" -> return "Husky siberiano"
            "dalmatian" -> return "dálmata"
            "affenpinscher" -> return "affenpinscher"
            "basenji" -> return "basenji"
            "pug" -> return "doguillo"
            "Leonberg" -> return "Leonberg"
            "Newfoundland" -> return "Terranova"
            "Great Pyrenees" -> return "Los grandes pirineos"
            "Samoyed" -> return "Samoyedo"
            "Pomeranian" -> return "pomeranio"
            "chow" -> return "perro chino"
            "keeshond" -> return "Keeshond"
            "Brabancon griffon" -> return "Grifón de brabancon"
            "Pembroke" -> return "Pembroke"
            "Cardigan" -> return "Cárdigan"
            "toy poodle" -> return "poodle de juguete"
            "miniature poodle" -> return "caniche miniatura"
            "standard poodle" -> return "caniche estándar"
            "Mexican hairless" -> return "Mexicano sin pelo"
            "timber wolf" -> return "Lobo de madera"
            "white wolf" -> return "Lobo blanco"
            "red wolf" -> return "Lobo rojo"
            "coyote" -> return "coyote"
            "dingo" -> return "dingo"
            "dhole" -> return "dhole"
            "African hunting dog" -> return "Perro de caza africano"
            "hyena" -> return "hiena"
            "red fox" -> return "zorro rojo"
            "kit fox" -> return "kit de zorro"
            "Arctic fox" -> return "zorro ártico"
            "grey fox" -> return "zorro gris"
            "tabby" -> return "atigrado"
            "tiger cat" -> return "gato tigre"
            "Persian cat" -> return "gato persa"
            "Siamese cat" -> return "gato siames"
            "Egyptian cat" -> return "Gato egipcio"
            "cougar" -> return "Puma"
            "lynx" -> return "lince"
            "leopard" -> return "leopardo"
            "snow leopard" -> return "leopardo de nieve"
            "jaguar" -> return "jaguar"
            "lion" -> return "león"
            "tiger" -> return "Tigre"
            "cheetah" -> return "leopardo"
            "brown bear" -> return "oso café"
            "American black bear" -> return "Oso negro americano"
            "ice bear" -> return "oso de hielo"
            "sloth bear" -> return "oso perezoso"
            "mongoose" -> return "mangosta"
            "meerkat" -> return "suricata"
            "tiger beetle" -> return "escarabajo tigre"
            "ladybug" -> return "mariquita"
            "ground beetle" -> return "escarabajo de tierra"
            "long-horned beetle" -> return "escarabajo de cuernos largos"
            "leaf beetle" -> return "escarabajo"
            "dung beetle" -> return "escarabajo de estiércol"
            "rhinoceros beetle" -> return "Escarabajo rinoceronte"
            "weevil" -> return "gorgojo"
            "fly" -> return "mosca"
            "bee" -> return "abeja"
            "ant" -> return "hormiga"
            "grasshopper" -> return "saltamontes"
            "cricket" -> return "Grillo"
            "walking stick" -> return "bastón"
            "cockroach" -> return "cucaracha"
            "mantis" -> return "mantis"
            "cicada" -> return "cigarra"
            "leafhopper" -> return "saltamontes"
            "lacewing" -> return "Lacewing"
            "dragonfly" -> return "libélula"
            "damselfly" -> return "caballito del diablo"
            "admiral" -> return "almirante"
            "ringlet" -> return "rizo"
            "monarch" -> return "monarca"
            "cabbage butterfly" -> return "mariposa de la col"
            "sulphur butterfly" -> return "mariposa de azufre"
            "lycaenid" -> return "lycaenid"
            "starfish" -> return "estrella de mar"
            "sea urchin" -> return "erizo de mar"
            "sea cucumber" -> return "pepino de mar"
            "wood rabbit" -> return "conejo de madera"
            "hare" -> return "liebre"
            "Angora" -> return "Angora"
            "hamster" -> return "hámster"
            "porcupine" -> return "puerco espín"
            "fox squirrel" -> return "ardilla zorro"
            "marmot" -> return "marmota"
            "beaver" -> return "castor"
            "guinea pig" -> return "conejillo de indias"
            "sorrel" -> return "Alazán"
            "zebra" -> return "cebra"
            "hog" -> return "cerdo"
            "wild boar" -> return "Jabalí"
            "warthog" -> return "jabalí"
            "hippopotamus" -> return "hipopótamo"
            "ox" -> return "buey"
            "water buffalo" -> return "búfalo de agua"
            "bison" -> return "bisonte"
            "ram" -> return "RAM"
            "bighorn" -> return "cuerno grande"
            "ibex" -> return "cabra montés"
            "hartebeest" -> return "hartebeest"
            "impala" -> return "impala"
            "gazelle" -> return "gacela"
            "Arabian camel" -> return "Camello árabe"
            "llama" -> return "llama"
            "weasel" -> return "comadreja"
            "mink" -> return "visón"
            "polecat" -> return "turón"
            "black-footed ferret" -> return "hurón de patas negras"
            "otter" -> return "nutria"
            "skunk" -> return "zorrillo"
            "badger" -> return "tejón"
            "armadillo" -> return "armadillo"
            "three-toed sloth" -> return "perezoso de tres dedos"
            "orangutan" -> return "orangután"
            "gorilla" -> return "gorila"
            "chimpanzee" -> return "chimpancé"
            "gibbon" -> return "gibón"
            "siamang" -> return "siamang"
            "guenon" -> return "guenon"
            "patas" -> return "patas"
            "baboon" -> return "babuino"
            "macaque" -> return "macaco"
            "langur" -> return "langur"
            "colobus" -> return "colobo"
            "proboscis monkey" -> return "mono probóscide"
            "marmoset" -> return "tití"
            "capuchin" -> return "capucho"
            "howler monkey" -> return "mono aullador"
            "titi" -> return "titi"
            "spider monkey" -> return "mono araña"
            "squirrel monkey" -> return "mono ardilla"
            "Madagascar cat" -> return "Gato de Madagascar"
            "indri" -> return "indri"
            "Indian elephant" -> return "Elefante indio"
            "African elephant" -> return "elefante africano"
            "lesser panda" -> return "panda menor"
            "giant panda" -> return "Panda gigante"
            "barracouta" -> return "barracouta"
            "eel" -> return "Anguila"
            "coho" -> return "coho"
            "rock beauty" -> return "belleza de roca"
            "anemone fish" -> return "pez anémona"
            "sturgeon" -> return "esturión"
            "gar" -> return "gar"
            "lionfish" -> return "pez león"
            "puffer" -> return "fumador"
            "abacus" -> return "ábaco"
            "abaya" -> return "abaya"
            "academic gown" -> return "bata académica"
            "accordion" -> return "acordeón"
            "acoustic guitar" -> return "guitarra acustica"
            "aircraft carrier" -> return "portaaviones"
            "airliner" -> return "avión de línea"
            "airship" -> return "dirigible"
            "altar" -> return "altar"
            "ambulance" -> return "ambulancia"
            "amphibian" -> return "anfibio"
            "analog clock" -> return "reloj analogo"
            "apiary" -> return "colmenar"
            "apron" -> return "delantal"
            "ashcan" -> return "cubo de la basura"
            "assault rifle" -> return "fusil de asalto"
            "backpack" -> return "mochila"
            "bakery" -> return "panadería"
            "balance beam" -> return "viga de equilibrio"
            "balloon" -> return "globo"
            "ballpoint" -> return "bolígrafo"
            "Band Aid" -> return "Apósito adhesivo"
            "banjo" -> return "banjo"
            "bannister" -> return "barandilla"
            "barbell" -> return "barra con pesas"
            "barber chair" -> return "silla de barbero"
            "barbershop" -> return "barbería"
            "barn" -> return "granero"
            "barometer" -> return "barómetro"
            "barrel" -> return "barril"
            "barrow" -> return "carretilla"
            "baseball" -> return "béisbol"
            "basketball" -> return "baloncesto"
            "bassinet" -> return "moisés"
            "bassoon" -> return "fagot"
            "bathing cap" -> return "gorro de baño"
            "bath towel" -> return "toalla de baño"
            "bathtub" -> return "bañera"

            "beach wagon" -> return "carro de playa"
            "beacon" -> return "Faro"
            "beaker" -> return "cubilete"
            "bearskin" -> return "piel de oso"
            "beer bottle" -> return "botella de cerveza"
            "beer glass" -> return "vaso de cerveza"
            "bell cote" -> return "campana"
            "bib" -> return "babero"
            "bicycle-built-for-two" -> return "bicicleta construida para dos"
            "bikini" -> return "bikini"
            "binder" -> return "aglutinante"
            "binoculars" -> return "prismáticos"
            "birdhouse" -> return "pajarera"
            "boathouse" -> return "cobertizo"
            "bobsled" -> return "bobsleigh"
            "bolo tie" -> return "corbata de bolo"
            "bonnet" -> return "capó"
            "bookcase" -> return "librero"
            "bookshop" -> return "librería"
            "bottlecap" -> return "tapón de botella"
            "bow" -> return "arco"
            "bow tie" -> return "corbata de moño"
            "brass" -> return "latón"
            "brassiere" -> return "sostén"
            "breakwater" -> return "rompeolas"
            "breastplate" -> return "coraza"
            "broom" -> return "Escoba"
            "bucket" -> return "Cubeta"
            "buckle" -> return "hebilla"
            "bulletproof vest" -> return "chaleco antibalas"
            "bullet train" -> return "tren bala"
            "butcher shop" -> return "carnicería"
            "cab" -> return "taxi"
            "caldron" -> return "hechicera"
            "candle" -> return "vela"
            "cannon" -> return "cañón"
            "canoe" -> return "canoa"
            "can opener" -> return "abrelatas"
            "cardigan" -> return "cárdigan"
            "car mirror" -> return "espejo de coche"
            "carousel" -> return "carrusel"
            "carpenter's kit" -> return "kit de carpintero"
            "carton" -> return "caja de cartón"
            "car wheel" -> return "Llanta de carro"
            "cash machine" -> return "cajero automático"
            "cassette" -> return "casete"
            "cassette player" -> return "reproductor de cassette"
            "castle" -> return "castillo"
            "catamaran" -> return "catamarán"
            "CD player" -> return "reproductor de CD"
            "cello" -> return "violonchelo"
            "cellular telephone" -> return "telefono celular"
            "chain" -> return "cadena"
            "chainlink fence" -> return "cerca de alambre"
            "chain mail" -> return "correo en cadena"
            "chain saw" -> return "sierra de cadena"
            "chest" -> return "cofre"
            "chiffonier" -> return "chifonier"
            "chime" -> return "repicar"
            "china cabinet" -> return "gabinete de China"
            "Christmas stocking" -> return "calcetín navideño"
            "church" -> return "Iglesia"
            "cinema" -> return "cine"
            "cleaver" -> return "cuchilla de carnicero"
            "cliff dwelling" -> return "vivienda del acantilado"
            "cloak" -> return "capa"
            "clog" -> return "obstruir"
            "cocktail shaker" -> return "batidor de coctéles"
            "coffee mug" -> return "taza de café"
            "coffeepot" -> return "cafetera"
            "coil" -> return "bobina"
            "combination lock" -> return "cerradura de combinación"
            "computer keyboard" -> return "teclado"
            "confectionery" -> return "confitería"
            "container ship" -> return "barco mercante"
            "convertible" -> return "convertible"
            "corkscrew" -> return "sacacorchos"
            "cornet" -> return "cucurucho"
            "cowboy boot" -> return "bota de vaquero"
            "cowboy hat" -> return "sombrero de vaquero"
            "cradle" -> return "cuna"
            "crane" -> return "grua"
            "crash helmet" -> return "casco protector"
            "crate" -> return "caja"
            "crib" -> return "cuna"
            "Crock Pot" -> return "Olla de barro"
            "croquet ball" -> return "pelota de croquet"
            "crutch" -> return "muleta"
            "cuirass" -> return "coraza"
            "dam" -> return "represa"
            "desk" -> return "escritorio"
            "desktop computer" -> return "computadora de escritorio"
            "dial telephone" -> return "marcar telefono"
            "diaper" -> return "pañal"
            "digital clock" -> return "reloj digital"
            "digital watch" -> return "reloj digital"
            "dining table" -> return "comedor"
            "dishrag" -> return "trapo para fregar platos"
            "dishwasher" -> return "lavavajillas"
            "disk brake" -> return "frenos de disco"
            "dock" -> return "muelle"
            "dogsled" -> return "trineo de perros"
            "dome" -> return "Hazme"
            "doormat" -> return "felpudo"
            "drilling platform" -> return "plataforma de perforación"
            "drum" -> return "tambor"
            "drumstick" -> return "palillo de tambor"
            "dumbbell" -> return "pesa"
            "Dutch oven" -> return "horno holandés"
            "electric fan" -> return "ventilador eléctrico"
            "electric guitar" -> return "guitarra electrica"
            "electric locomotive" -> return "locomotora electrica"
            "entertainment center" -> return "Centro de entretenimiento"
            "envelope" -> return "sobre"
            "espresso maker" -> return "cafetera espresso"
            "face powder" -> return "polvo facial"
            "feather boa" -> return "Boa de plumas"
            "file" -> return "archivo"
            "fireboat" -> return "barco de bomberos"
            "fire engine" -> return "camion de bomberos"
            "fire screen" -> return "pantalla de fuego"
            "flagpole" -> return "asta de bandera"
            "flute" -> return "flauta"
            "folding chair" -> return "silla plegable"
            "football helmet" -> return "casco de fútbol"
            "forklift" -> return "máquina elevadora"
            "fountain" -> return "fuente"
            "fountain pen" -> return "Pluma fuente"
            "four-poster" -> return "cuatro carteles"
            "freight car" -> return "vagón de carga"
            "French horn" -> return "cuerno francés"
            "frying pan" -> return "sartén"
            "fur coat" -> return "abrigo de piel"
            "garbage truck" -> return "camión de la basura"
            "gasmask" -> return "máscara de gas"
            "gas pump" -> return "bomba de gas"
            "goblet" -> return "copa"
            "go-kart" -> return "go-kart"
            "golf ball" -> return "pelota de golf"
            "golfcart" -> return "carro de golf"
            "gondola" -> return "góndola"
            "gong" -> return "gong"
            "gown" -> return "vestido"
            "grand piano" -> return "piano de cola"
            "greenhouse" -> return "invernadero"
            "grille" -> return "reja"
            "grocery store" -> return "tienda de comestibles"
            "guillotine" -> return "guillotina"
            "hair slide" -> return "diapositiva de pelo"
            "hair spray" -> return "spray para el cabello"
            "half track" -> return "media pista"
            "hammer" -> return "martillo"
            "hamper" -> return "cesto"
            "hand blower" -> return "soplador de mano"
            "hand-held computer" -> return "computadora de mano"
            "handkerchief" -> return "pañuelo"
            "hard disc" -> return "disco duro"
            "harmonica" -> return "harmónica"
            "harp" -> return "arpa"
            "harvester" -> return "segador"
            "hatchet" -> return "hacha"
            "holster" -> return "funda"
            "home theater" -> return "cine en casa"
            "honeycomb" -> return "panal"
            "hook" -> return "gancho"
            "hoopskirt" -> return "hoopskirt"
            "horizontal bar" -> return "barra horizontal"
            "horse cart" -> return "carro de caballos"
            "hourglass" -> return "reloj de arena"
            "iPod" -> return "iPod"
            "iron" -> return "hierro"
            "jack-o'-lantern" -> return "Jack-o'-lantern"
            "jean" -> return "vaquero"
            "jeep" -> return "todoterreno"
            "jersey" -> return "jersey"
            "jigsaw puzzle" -> return "rompecabezas"
            "jinrikisha" -> return "jinrikisha"
            "joystick" -> return "palanca de mando"
            "kimono" -> return "kimono"
            "knee pad" -> return "rodillera"
            "knot" -> return "nudo"
            "lab coat" -> return "bata de laboratorio"
            "ladle" -> return "cucharón"
            "lampshade" -> return "pantalla de lámpara"
            "laptop" -> return "ordenador portátil"
            "lawn mower" -> return "cortacésped"
            "lens cap" -> return "tapa de la lente"
            "letter opener" -> return "abrecartas"
            "library" -> return "biblioteca"
            "lifeboat" -> return "bote salvavidas"
            "lighter" -> return "encendedor"
            "limousine" -> return "limusina"
            "liner" -> return "transatlántico"
            "lipstick" -> return "lápiz labial"
            "Loafer" -> return "Mocasín"
            "lotion" -> return "loción"
            "loudspeaker" -> return "altoparlante"
            "loupe" -> return "lupa"
            "lumbermill" -> return "Serreria"
            "magnetic compass" -> return "brújula"
            "mailbag" -> return "saca de correos"
            "mailbox" -> return "buzón"
            "maillot" -> return "maillot"
            "maillot" -> return "maillot"
            "manhole cover" -> return "tapa de registro"
            "maraca" -> return "maraca"
            "marimba" -> return "marimba"
            "mask" -> return "máscara"
            "matchstick" -> return "fósforo"
            "maypole" -> return "mayo"
            "maze" -> return "laberinto"
            "measuring cup" -> return "taza medidora"
            "medicine chest" -> return "botiquin"
            "megalith" -> return "megalito"
            "microphone" -> return "micrófono"
            "microwave" -> return "microondas"
            "military uniform" -> return "uniforme militar"
            "milk can" -> return "la leche puede"
            "minibus" -> return "microbús"
            "miniskirt" -> return "minifalda"
            "minivan" -> return "minivan"
            "missile" -> return "misil"
            "mitten" -> return "mitón"
            "mixing bowl" -> return "tazón para mezclar"
            "mobile home" -> return "casa móvil"
            "Model T" -> return "Modelo t"
            "modem" -> return "módem"
            "monastery" -> return "monasterio"
            "monitor" -> return "monitor"
            "moped" -> return "ciclomotor"
            "mortar" -> return "mortero"
            "mortarboard" -> return "birrete"
            "mosque" -> return "mezquita"
            "mosquito net" -> return "mosquitero"
            "motor scooter" -> return "motor de scooter"
            "mountain bike" -> return "bicicleta de montaña"
            "mountain tent" -> return "tienda de montaña"
            "mouse" -> return "ratón"
            "mousetrap" -> return "ratonera"
            "moving van" -> return "van en movimiento"
            "muzzle" -> return "bozal"
            "nail" -> return "uña"
            "neck brace" -> return "collarín"
            "necklace" -> return "collar"
            "nipple" -> return "pezón"
            "notebook" -> return "cuaderno"
            "obelisk" -> return "obelisco"
            "oboe" -> return "oboe"
            "ocarina" -> return "ocarina"
            "odometer" -> return "cuentakilómetros"
            "oil filter" -> return "filtro de aceite"
            "organ" -> return "Organo"
            "oscilloscope" -> return "osciloscopio"
            "overskirt" -> return "sobrefalda"
            "oxcart" -> return "carreta"
            "oxygen mask" -> return "mascara de oxigeno"
            "packet" -> return "paquete"
            "paddle" -> return "paleta"
            "paddlewheel" -> return "Rueda de paletas"
            "padlock" -> return "candado"
            "paintbrush" -> return "Cepillo de pintura"
            "pajama" -> return "pijama"
            "palace" -> return "palacio"
            "panpipe" -> return "zampoña"
            "paper towel" -> return "toalla de papel"
            "parachute" -> return "paracaídas"
            "parallel bars" -> return "barras paralelas"
            "park bench" -> return "Banco del parque"
            "parking meter" -> return "parquímetro"
            "passenger car" -> return "coche de pasajeros"
            "patio" -> return "patio"
            "pay-phone" -> return "teléfono público de monedas"
            "pedestal" -> return "pedestal"
            "pencil box" -> return "caja de lápices"
            "pencil sharpener" -> return "sacapuntas"
            "perfume" -> return "perfume"
            "Petri dish" -> return "placa de Petri"
            "photocopier" -> return "fotocopiadora"
            "pick" -> return "recoger"
            "pickelhaube" -> return "pickelhaube"
            "picket fence" -> return "cerca de piquete"
            "pickup" -> return "recoger"
            "pier" -> return "muelle"
            "piggy bank" -> return "hucha"
            "pill bottle" -> return "pastillero"
            "pillow" -> return "almohada"
            "ping-pong ball" -> return "pelota de ping pong"
            "pinwheel" -> return "molinillo"
            "pirate" -> return "pirata"
            "pitcher" -> return "lanzador"
            "plane" -> return "avión"
            "planetarium" -> return "planetario"
            "plastic bag" -> return "bolsa de plastico"
            "plate rack" -> return "escurreplatos"
            "plow" -> return "arado"
            "plunger" -> return "émbolo"
            "Polaroid camera" -> return "cámara Polaroid"
            "pole" -> return "polo"
            "police van" -> return "furgoneta de policia"
            "poncho" -> return "poncho"
            "pool table" -> return "mesa de billar"
            "pop bottle" -> return "botella pop"
            "pot" -> return "maceta"
            "potter's wheel" -> return "rueda de alfarero"
            "power drill" -> return "taladro eléctrico"
            "prayer rug" -> return "alfombra de rezo"
            "printer" -> return "impresora"
            "prison" -> return "prisión"
            "projectile" -> return "proyectil"
            "projector" -> return "proyector"
            "puck" -> return "disco"
            "punching bag" -> return "saco de boxeo"
            "purse" -> return "bolso"
            "quill" -> return "pluma"
            "quilt" -> return "edredón"
            "racer" -> return "corredor"
            "racket" -> return "raqueta"
            "radiator" -> return "radiador"
            "radio" -> return "radio"
            "radio telescope" -> return "Radio telescopio"
            "rain barrel" -> return "barril de lluvia"
            "recreational vehicle" -> return "vehículo recreacional"
            "reel" -> return "carrete"
            "reflex camera" -> return "cámara réflex"
            "refrigerator" -> return "refrigerador"
            "remote control" -> return "control remoto"
            "restaurant" -> return "restaurante"
            "revolver" -> return "revólver"
            "rifle" -> return "rifle"
            "rocking chair" -> return "mecedora"
            "rotisserie" -> return "asador"
            "rubber eraser" -> return "goma de borrar"
            "rugby ball" -> return "Pelota de rugby"
            "rule" -> return "regla"
            "running shoe" -> return "Zapatos para correr"
            "safe" -> return "seguro"
            "safety pin" -> return "perno de seguridad"
            "saltshaker" -> return "salero"
            "sandal" -> return "sandalia"
            "sarong" -> return "pareo de malasia"
            "sax" -> return "saxófono"
            "scabbard" -> return "vaina"
            "scale" -> return "escala"
            "school bus" -> return "autobús escolar"
            "schooner" -> return "goleta"
            "scoreboard" -> return "marcador"
            "screen" -> return "pantalla"
            "screw" -> return "tornillo"
            "screwdriver" -> return "destornillador"
            "seat belt" -> return "cinturón de seguridad"
            "sewing machine" -> return "máquina de coser"
            "shield" -> return "proteger"
            "shoe shop" -> return "tienda de zapatos"
            "shoji" -> return "shoji"
            "shopping basket" -> return "cesta de la compra"
            "shopping cart" -> return "carrito de compras"
            "shovel" -> return "pala"
            "shower cap" -> return "gorro de ducha"
            "shower curtain" -> return "cortina de la ducha"
            "ski" -> return "esquí"
            "ski mask" -> return "máscara de esquí"
            "sleeping bag" -> return "bolsa de dormir"
            "slide rule" -> return "regla de cálculo"
            "sliding door" -> return "puerta corrediza"
            "slot" -> return "espacio"
            "snorkel" -> return "tubo respirador"
            "snowmobile" -> return "motonieve"
            "snowplow" -> return "quitanieves"
            "soap dispenser" -> return "dispensador de jabón"
            "soccer ball" -> return "balón de fútbol"
            "sock" -> return "calcetín"
            "solar dish" -> return "plato solar"
            "sombrero" -> return "sombrero"
            "soup bowl" -> return "tazón de sopa"
            "space bar" -> return "barra espaciadora"
            "space heater" -> return "calentador"
            "space shuttle" -> return "transbordador espacial"
            "spatula" -> return "espátula"
            "speedboat" -> return "lancha rápida"
            "spider web" -> return "telaraña"
            "spindle" -> return "huso"
            "sports car" -> return "coche deportivo"
            "spotlight" -> return "destacar"
            "stage" -> return "etapa"
            "steam locomotive" -> return "locomotora de vapor"
            "steel arch bridge" -> return "puente de arco de acero"
            "steel drum" -> return "tambor de acero"
            "stethoscope" -> return "estetoscopio"
            "stole" -> return "robó"
            "stone wall" -> return "Pared de piedra"
            "stopwatch" -> return "cronógrafo"
            "stove" -> return "estufa"
            "strainer" -> return "colador"
            "streetcar" -> return "tranvía"
            "stretcher" -> return "camilla"
            "studio couch" -> return "sofá de estudio"
            "stupa" -> return "estupa"
            "submarine" -> return "submarino"
            "suit" -> return "traje"
            "sundial" -> return "reloj de sol"
            "sunglass" -> return "gafas de sol"
            "sunglasses" -> return "Gafas de sol"
            "sunscreen" -> return "protector solar"
            "suspension bridge" -> return "puente colgante"
            "swab" -> return "torunda"
            "sweatshirt" -> return "camisa de entrenamiento"
            "swimming trunks" -> return "shorts de baño"
            "swing" -> return "columpio"
            "switch" -> return "cambiar"
            "syringe" -> return "jeringuilla"
            "table lamp" -> return "Lámpara de mesa"
            "tank" -> return "tanque"
            "tape player" -> return "reproductor de cintas"
            "teapot" -> return "tetera"
            "teddy" -> return "osito de peluche"
            "television" -> return "televisión"
            "tennis ball" -> return "Pelota de tenis"
            "thatch" -> return "paja"
            "theater curtain" -> return "cortina de teatro"
            "thimble" -> return "dedal"
            "thresher" -> return "trilladora"
            "throne" -> return "trono"
            "tile roof" -> return "teja"
            "toaster" -> return "tostadora"
            "tobacco shop" -> return "tienda de tabaco"
            "toilet seat" -> return "asiento del baño"
            "torch" -> return "antorcha"
            "totem pole" -> return "tótem"
            "tow truck" -> return "camión de remolque"
            "toyshop" -> return "tienda de juguetes"
            "tractor" -> return "tractor"
            "trailer truck" -> return "camión de remolque"
            "tray" -> return "bandeja"
            "trench coat" -> return "gabardina"
            "tricycle" -> return "triciclo"
            "trimaran" -> return "trimarán"
            "tripod" -> return "trípode"
            "triumphal arch" -> return "arco triunfal"
            "trolleybus" -> return "trolebús"
            "trombone" -> return "trombón"
            "tub" -> return "tina"
            "turnstile" -> return "torniquete"
            "typewriter keyboard" -> return "teclado de máquina de escribir"
            "umbrella" -> return "paraguas"
            "unicycle" -> return "monociclo"
            "upright" -> return "vertical"
            "vacuum" -> return "vacío"
            "vase" -> return "florero"
            "vault" -> return "bóveda"
            "velvet" -> return "terciopelo"
            "vending machine" -> return "máquina expendedora"
            "vestment" -> return "vestimenta"
            "viaduct" -> return "viaducto"
            "violin" -> return "violín"
            "volleyball" -> return "vóleibol"
            "waffle iron" -> return "gofrera"
            "wall clock" -> return "reloj de pared"
            "wallet" -> return "billetera"
            "wardrobe" -> return "guardarropa"
            "warplane" -> return "avión de guerra"
            "washbasin" -> return "lavabo"
            "washer" -> return "lavadora"
            "water bottle" -> return "botella de agua"
            "water jug" -> return "jarra de agua"
            "water tower" -> return "Torre de agua"
            "whiskey jug" -> return "jarra de whisky"
            "whistle" -> return "silbar"
            "wig" -> return "peluca"
            "window screen" -> return "pantalla de la ventana"
            "window shade" -> return "persiana"
            "Windsor tie" -> return "Corbata Windsor"
            "wine bottle" -> return "botella de vino"
            "wing" -> return "ala"
            "wok" -> return "wok"
            "wooden spoon" -> return "cuchara de madera"
            "wool" -> return "lana"
            "worm fence" -> return "cerca de gusanos"
            "wreck" -> return "ruina"
            "yawl" -> return "yola"
            "yurt" -> return "yurta"
            "web site" -> return "sitio web"
            "comic book" -> return "cómic"
            "crossword puzzle" -> return "crucigrama"
            "street sign" -> return "cartel de la calle"
            "traffic light" -> return "semáforo"
            "book jacket" -> return "solapa del libro"
            "menu" -> return "menú"
            "plate" -> return "plato"
            "guacamole" -> return "guacamole"
            "consomme" -> return "consomé"
            "hot pot" -> return "olla caliente"
            "trifle" -> return "nimiedad"
            "ice cream" -> return "helado"
            "ice lolly" -> return "paleta"
            "French loaf" -> return "pan francés"
            "bagel" -> return "rosquilla"
            "pretzel" -> return "galleta salada"
            "cheeseburger" -> return "hamburguesa con queso"
            "hotdog" -> return "Pancho"
            "mashed potato" -> return "puré de patatas"
            "head cabbage" -> return "repollo"
            "broccoli" -> return "brócoli"
            "cauliflower" -> return "coliflor"
            "zucchini" -> return "calabacín"
            "spaghetti squash" -> return "calabaza espagueti"
            "acorn squash" -> return "calabaza bellota"
            "butternut squash" -> return "calabaza moscada"
            "cucumber" -> return "Pepino"
            "artichoke" -> return "alcachofa"
            "bell pepper" -> return "pimiento"
            "cardoon" -> return "cardo"
            "mushroom" -> return "seta"
            "Granny Smith" -> return "Granny Smith"
            "strawberry" -> return "fresa"
            "orange" -> return "naranja"
            "lemon" -> return "limón"
            "fig" -> return "higo"
            "pineapple" -> return "piña"
            "banana" -> return "plátano"
            "jackfruit" -> return "jaca"
            "custard apple" -> return "chirimoya"
            "pomegranate" -> return "granada"
            "hay" -> return "heno"
            "carbonara" -> return "carbonara"
            "chocolate sauce" -> return "salsa de chocolate"
            "dough" -> return "masa"
            "meat loaf" -> return "pastel de carne"
            "pizza" -> return "Pizza"
            "potpie" -> return "pastel de carne"
            "burrito" -> return "burrito"
            "red wine" -> return "vino tinto"
            "espresso" -> return "Café exprés"
            "cup" -> return "taza"
            "eggnog" -> return "Ponche de huevo"
            "alp" -> return "montaña"
            "bubble" -> return "burbuja"
            "cliff" -> return "acantilado"
            "coral reef" -> return "Arrecife de coral"
            "geyser" -> return "géiser"
            "lakeside" -> return "orilla del lago"
            "promontory" -> return "promontorio"
            "sandbar" -> return "banco de arena"
            "seashore" -> return "costa"
            "valley" -> return "Valle"
            "volcano" -> return "volcán"
            "ballplayer" -> return "jugador de pelota"
            "groom" -> return "novio"
            "scuba diver" -> return "buzo"
            "rapeseed" -> return "colza"
            "daisy" -> return "margarita"
            "yellow lady's slipper" -> return "zapatilla de dama amarilla"
            "corn" -> return "maíz"
            "acorn" -> return "bellota"
            "hip" -> return "cadera"
            "buckeye" -> return "castaño de indias"
            "coral fungus" -> return "hongo de coral"
            "agaric" -> return "agárico"
            "gyromitra" -> return "Gyromitra"
            "stinkhorn" -> return "stinkhorn"
            "earthstar" -> return "earthstar"
            "hen-of-the-woods" -> return "gallina del bosque"
            "bolete" -> return "bolete"
            "ear" -> return "oído"
            "toilet tissue" -> return "papel de baño"
            else -> return "No traducido"

            
        }
    }
}